### PR TITLE
Implement password rules for REST Api

### PR DESCRIPTION
**Pull request by floragunncom**

### CODE REVIEW

**Comment by nibix** [comment]
@floragunncom This way, calling the PATCH method will cause validation to be performed on all users, even if only one user is patched. I understand that most validations will be normally no-ops, as the existing users will normally have no password attribute, but only the hash attribute. However, if for some reason someone manages to bypass the REST API and directly patches the ES index to have a user with an invalid password attribute, this will cause PATCH calls to fail in an unobvious way.

So, at least I'd recommend to move the new validation inside the block guarded by

`if (oldResource == null || !oldResource.equals(patchedResource)) {`

Still, this looks a bit weird because the same validation is done twice directly in sequence. Once on the  unprocessed data and once on the processed data. Maybe, a more elegant solution would be to add a flag to PatchableResourceApiAction which controls whether validation is performed before or after processing.

**Comment by floragunncom** [comment]
@nibix thx

**Comment by nibix** [comment]
@floragunncom Actually, I'm wondering whether it would be feasible to move validation in front of the postProcessApplyPatchResult() call. Right now, I cannot think of any reason against it. This would save us a bit of complexity.

**Comment by floragunncom** [comment]
@nibix can you take over here and move the validation as suggested? Just commit into this PR.

**Comment by floragunncom** [comment]
For discussed cleanup of validation see ITT-1793

**Pull request merged**
